### ISSUE TITLE
No configurations found

### ISSUE THREAD

**Issue by prasadacharya26** [mihir0699/FoodEazy#2]
WARNING: No configurations found in configuration directory:C:\Users\Prasad\Downloads\FoodEazy-master\FoodEazy-master\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
C:\Users\Prasad\Downloads\FoodEazy-master\FoodEazy-master\node_modules\config\lib\config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "mongodb+srv://prasad:prasad@cluster0.hnhzs.mongodb.net/FoodEaszy?retryWrites=true" is not defined
    at Config.get (C:\Users\Prasad\Downloads\FoodEazy-master\FoodEazy-master\node_modules\config\lib\config.js:182:11)       
    at connectDB (C:\Users\Prasad\Downloads\FoodEazy-master\FoodEazy-master\config\db.js:6:21)
    at Object.<anonymous> (C:\Users\Prasad\Downloads\FoodEazy-master\FoodEazy-master\server.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47

**Comment by BreathinLife** [comment]
@prasadacharya26  getting same error while learning and  coding. 
Error: Configuration property "mongodb//localhost:27017/" is not defined
    at Config.get (C:\Users\nb199\Desktop\tuesday\FoodEazy\node_modules\config\lib\config.js:182:11)    at connectDB (C:\Users\nb199\Desktop\tuesday\FoodEazy\config\db.js:6:21)
    at Object.<anonymous> (C:\Users\nb199\Desktop\tuesday\FoodEazy\server.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
PS C:\Users\nb199\Desktop\tuesday\FoodEazy> node server.js
